<?php

namespace App\Admin\Controllers;

use App\Admin\Repositories\FailedJob;
use Dcat\Admin\Form;
use Dcat\Admin\Grid;
use Dcat\Admin\Layout\Content;
use Dcat\Admin\Show;
use Dcat\Admin\Http\Controllers\AdminController;

class FailedJobController extends AdminController
{
    public function index(Content $content)
    {

        return parent::index($content); // TODO: Change the autogenerated stub
    }

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {

        return Grid::make(new FailedJob(), function (Grid $grid) {
            $grid->column('id')->sortable();
            $grid->column('connection');
            $grid->column('queue');
            $grid->column('payload');
            $grid->column('exception');
            $grid->column('failed_at');
            $grid->filter(function (Grid\Filter $filter) {
                $filter->equal('id');

            });
        });
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     *
     * @return Show
     */
    protected function detail($id)
    {
        return Show::make($id, new FailedJob(), function (Show $show) {
            $show->field('id');
            $show->field('connection');
            $show->field('queue');
            $show->field('payload');
            $show->field('exception');
            $show->field('failed_at');
        });
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Form::make(new FailedJob(), function (Form $form) {
            $form->display('id');
            $form->text('connection');
            $form->text('queue');
            $form->text('payload');
            $form->text('exception');
            $form->text('failed_at');
        });
    }
}
